platform :ios, '9.0'
use_frameworks!

target 'RxSwiftX_Example' do
  pod 'RxSwiftX', :path => '../'
  pod 'RxSwiftX/DataSources', :path => '../'
  pod 'RxSwiftX/Network', :path => '../'
  pod 'RxSwiftX/MJRefresh', :path => '../'

  target 'RxSwiftX_Tests' do
    inherit! :search_paths

    
  end
end
